#! /bin/bash

/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.picking.csv --model=stock.picking --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore= --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_receipt_error.log 2>&1
/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.picking.csv --model=stock.picking --encoding=utf-8 --ignore= --sep=";" --context="{'tracking_disable': True}"

/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.move.lot.numbers.csv --model=stock.production.lot --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore= --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_lot_number_error.log 2>&1
/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.move.lot.numbers.csv --model=stock.production.lot --encoding=utf-8 --ignore= --sep=";" --context="{'tracking_disable': True}"

/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv --model=stock.move --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore= --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_receipt_move_error.log 2>&1
/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv --model=stock.move --encoding=utf-8 --ignore= --sep=";" --context="{'tracking_disable': True}"

/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.line.move.csv --model=stock.move.line --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore= --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_receipt_line_error.log 2>&1
/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.line.move.csv --model=stock.move.line --encoding=utf-8 --ignore= --sep=";" --context="{'tracking_disable': True}"

## Import PO's again to confirm orders that are required
#sed -i 's/;"to approve"/;"purchase"/g' /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.csv
#/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.csv --model=purchase.order --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore="origin","name","partner_id/id","currency_id","date_order","payment_term_id","incoterm_id" --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_status_error.log 2>&1
#/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.csv --model=purchase.order --encoding=utf-8 --ignore="origin","name","partner_id/id","currency_id","date_order","payment_term_id","incoterm_id" --sep=";" --context="{'tracking_disable': True}"

#timestamp=$(date +'%y%m%d-%H%M')
#mkdir /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/*.log /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/o_logs_out/${timestamp}
#mv /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/*.log /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/o_logs_out/${timestamp}/
#mv /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/*.bis /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/o_logs_out/${timestamp}/


## Manual store for picking moves
## All fields: "id","picking_id/id","product_id/id","product_uom_qty","name","product_uom","location_id","location_dest_id","purchase_line_id/id","state","date","invoice_number"
## Ignore to change state only: "picking_id/id","product_id/id","product_uom_qty","name","product_uom","location_id","location_dest_id","purchase_line_id/id","date","invoice_number"
#sed -i 's/;"done"/;"draft"/g' /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv
#/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv --model=stock.move --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore= --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_receipt_move_error.log 2>&1
#/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv --model=stock.move --encoding=utf-8 --ignore= --sep=";" --context="{'tracking_disable': True}"
#sed -i 's/;"draft"/;"done"/g' /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv
#/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv --model=stock.move --encoding=utf-8 --worker=1 --size=20 --groupby= --ignore="picking_id/id","product_id/id","product_uom_qty","name","product_uom","location_id","location_dest_id","purchase_line_id/id","date","invoice_number" --sep=";" --context="{'tracking_disable': True}" > /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/po_receipt_move_error.log 2>&1
#/usr/bin/python3.9 -m odoo_import_thread -c /home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/conf/connection.conf --fail --file=/home/pi3ce/03_DevProjects/carezza_dev/carezza-design/import_assist/output_3/purchase.order.stock.move.csv --model=stock.move --encoding=utf-8 --ignore="picking_id/id","product_id/id","product_uom_qty","name","product_uom","location_id","location_dest_id","purchase_line_id/id","date","invoice_number" --sep=";" --context="{'tracking_disable': True}"

